query ShowList @loading {
  genres(delay: 2000) {
    edges {
      node {
        name
        shows {
          edges {
            node {
              id
              name
              billboard {
                source
              }
            }
          }
        }
      }
    }
  }
}
